package com.draw.database

import com.draw.R
import com.draw.model.AnimationGuide
import com.draw.model.TypeAnimationGuide

object DataClient {


    fun listBeginner(): MutableList<AnimationGuide> {
        return mutableListOf(
            AnimationGuide(
                R.string.beginner,
                R.drawable.frame_beginer_1,
                listOf(
                    R.drawable.frame_beginer_1,
                    R.drawable.frame_beginer_2
                )
            ),
            AnimationGuide(
                R.string.yayyy,
                R.drawable.frame_yayyy_1,
                listOf(
                    R.drawable.frame_yayyy_1,
                    R.drawable.frame_yayyy_2,
                    R.drawable.frame_yayyy_3,
                    R.drawable.frame_yayyy_4
                )
            ),

            AnimationGuide(
                R.string.duck_jump,
                R.drawable.frame_duck_jump_1,
                listOf(
                    R.drawable.frame_duck_jump_1,
                    R.drawable.frame_duck_jump_2,
                    R.drawable.frame_duck_jump_3,
                    R.drawable.frame_duck_jump_4,
                    R.drawable.frame_duck_jump_5
                )
            ),

            AnimationGuide(
                R.string.sun_rise,
                R.drawable.frame_sun_rise_1,
                listOf(
                    R.drawable.frame_sun_rise_1,
                    R.drawable.frame_sun_rise_2,
                    R.drawable.frame_sun_rise_3
                )
            ),

            AnimationGuide(
                R.string.straw_berry,
                R.drawable.frame_strawberry_1,
                listOf(
                    R.drawable.frame_strawberry_1,
                    R.drawable.frame_strawberry_2,
                    R.drawable.frame_strawberry_3,
                    R.drawable.frame_strawberry_4
                )
            ),

            AnimationGuide(
                R.string.jumping_ball,
                R.drawable.frame_jumping_aball_1,
                listOf(
                    R.drawable.frame_jumping_aball_1,
                    R.drawable.frame_jumping_aball_2,
                    R.drawable.frame_jumping_aball_3,
                    R.drawable.frame_jumping_aball_4,
                    R.drawable.frame_jumping_aball_5,
                    R.drawable.frame_jumping_aball_6,
                    R.drawable.frame_jumping_aball_7,
                    R.drawable.frame_jumping_aball_8
                )
            ),

            AnimationGuide(
                R.string.cute_bee,
                R.drawable.frame_cute_bee_1,
                listOf(
                    R.drawable.frame_cute_bee_1,
                    R.drawable.frame_cute_bee_2,
                    R.drawable.frame_cute_bee_3
                )
            ),

            AnimationGuide(
                R.string.baby_tree,
                R.drawable.frame_baby_tree_1,
                listOf(
                    R.drawable.frame_baby_tree_1,
                    R.drawable.frame_baby_tree_2,
                    R.drawable.frame_baby_tree_3,
                    R.drawable.frame_baby_tree_4,
                    R.drawable.frame_baby_tree_5,
                    R.drawable.frame_baby_tree_6
                )
            ),

            AnimationGuide(
                R.string.hug,
                R.drawable.frame_hug_1,
                listOf(
                    R.drawable.frame_hug_1,
                    R.drawable.frame_hug_2,
                    R.drawable.frame_hug_3,
                    R.drawable.frame_hug_4,
                    R.drawable.frame_hug_5,
                    R.drawable.frame_hug_6,
                    R.drawable.frame_hug_7,
                    R.drawable.frame_hug_8,
                    R.drawable.frame_hug_9,
                    R.drawable.frame_hug_10
                )
            ),

            AnimationGuide(
                R.string.drop_egg,
                R.drawable.frame_drop_egg_1,
                listOf(
                    R.drawable.frame_drop_egg_1,
                    R.drawable.frame_drop_egg_2,
                    R.drawable.frame_drop_egg_3,
                    R.drawable.frame_drop_egg_4,
                    R.drawable.frame_drop_egg_5,
                    R.drawable.frame_drop_egg_6,
                    R.drawable.frame_drop_egg_7,
                    R.drawable.frame_drop_egg_8,
                    R.drawable.frame_drop_egg_9,
                    R.drawable.frame_drop_egg_10,
                    R.drawable.frame_drop_egg_11,
                    R.drawable.frame_drop_egg_12,
                    R.drawable.frame_drop_egg_13,
                    R.drawable.frame_drop_egg_14
                )
            ),

            AnimationGuide(
                R.string.writing_note,
                R.drawable.frame_writing_1,
                listOf(
                    R.drawable.frame_writing_1,
                    R.drawable.frame_writing_2,
                    R.drawable.frame_writing_3,
                    R.drawable.frame_writing_4,
                    R.drawable.frame_writing_5,
                    R.drawable.frame_writing_6,
                    R.drawable.frame_writing_7,
                    R.drawable.frame_writing_8,
                    R.drawable.frame_writing_9,
                    R.drawable.frame_writing_10,
                    R.drawable.frame_writing_11,
                )
            ),

            AnimationGuide(
                R.string.sulked_chick,
                R.drawable.frame_sulked_chick_1,
                listOf(
                    R.drawable.frame_sulked_chick_1,
                    R.drawable.frame_sulked_chick_2,
                    R.drawable.frame_sulked_chick_3,
                    R.drawable.frame_sulked_chick_4,
                    R.drawable.frame_sulked_chick_5,
                    R.drawable.frame_sulked_chick_6,
                    R.drawable.frame_sulked_chick_7,
                    R.drawable.frame_sulked_chick_8,
                    R.drawable.frame_sulked_chick_9,
                    R.drawable.frame_sulked_chick_10,
                )
            ),
        )
    }

    fun listAnimal(): MutableList<AnimationGuide> {
        return mutableListOf(
            AnimationGuide(
                R.string.a_creator,
                R.drawable.frame_a_creator_1,
                listOf(
                    R.drawable.frame_a_creator_1,
                    R.drawable.frame_a_creator_2,
                    R.drawable.frame_a_creator_3,
                    R.drawable.frame_a_creator_4,
                    R.drawable.frame_a_creator_5,
                    R.drawable.frame_a_creator_6,
                    R.drawable.frame_a_creator_7,
                    R.drawable.frame_a_creator_8,
                    R.drawable.frame_a_creator_9,
                    R.drawable.frame_a_creator_10
                )
            ),

            AnimationGuide(
                R.string.an_angry_gift,
                R.drawable.frame_an_angry_gift_1,
                listOf(
                    R.drawable.frame_an_angry_gift_1,
                    R.drawable.frame_an_angry_gift_2,
                    R.drawable.frame_an_angry_gift_3,
                    R.drawable.frame_an_angry_gift_4,
                    R.drawable.frame_an_angry_gift_5,
                    R.drawable.frame_an_angry_gift_6,
                    R.drawable.frame_an_angry_gift_7,
                    R.drawable.frame_an_angry_gift_8,
                    R.drawable.frame_an_angry_gift_9,
                    R.drawable.frame_an_angry_gift_10,
                    R.drawable.frame_an_angry_gift_11,
                    R.drawable.frame_an_angry_gift_12,
                    R.drawable.frame_an_angry_gift_13
                )
            ),

            AnimationGuide(
                R.string.animal,
                R.drawable.frame_animal_1,
                listOf(
                    R.drawable.frame_animal_1,
                    R.drawable.frame_animal_2,
                    R.drawable.frame_animal_3,
                    R.drawable.frame_animal_4,
                    R.drawable.frame_animal_5,
                    R.drawable.frame_animal_6,
                    R.drawable.frame_animal_7,
                    R.drawable.frame_animal_8,
                    R.drawable.frame_animal_9,
                    R.drawable.frame_animal_10
                )
            ),

            AnimationGuide(
                R.string.cat_1,
                R.drawable.frame_cat_1_1,
                listOf(
                    R.drawable.frame_cat_1_1,
                    R.drawable.frame_cat_1_2,
                    R.drawable.frame_cat_1_3,
                    R.drawable.frame_cat_1_4,
                    R.drawable.frame_cat_1_5,
                    R.drawable.frame_cat_1_6,
                    R.drawable.frame_cat_1_7,
                    R.drawable.frame_cat_1_8,
                )
            ),

            AnimationGuide(
                R.string.cat_2,
                R.drawable.frame_cat_2_1,
                listOf(
                    R.drawable.frame_cat_2_1,
                    R.drawable.frame_cat_2_2,
                    R.drawable.frame_cat_2_3,
                    R.drawable.frame_cat_2_4,
                    R.drawable.frame_cat_2_5,
                    R.drawable.frame_cat_2_6,
                    R.drawable.frame_cat_2_7,
                    R.drawable.frame_cat_2_8,
                )
            ),

            AnimationGuide(
                R.string.cat_3,
                R.drawable.frame_cat_3_1,
                listOf(
                    R.drawable.frame_cat_3_1,
                    R.drawable.frame_cat_3_2,
                    R.drawable.frame_cat_3_3,
                    R.drawable.frame_cat_3_4,
                    R.drawable.frame_cat_3_5,
                    R.drawable.frame_cat_3_6,
                    R.drawable.frame_cat_3_7,
                )
            ),

            AnimationGuide(
                R.string.cat_4,
                R.drawable.frame_cat_4_1,
                listOf(
                    R.drawable.frame_cat_4_1,
                    R.drawable.frame_cat_4_2,
                    R.drawable.frame_cat_4_3,
                    R.drawable.frame_cat_4_4,
                    R.drawable.frame_cat_4_5,
                    R.drawable.frame_cat_4_6,
                    R.drawable.frame_cat_4_7,
                    R.drawable.frame_cat_4_8,
                )
            ),

            AnimationGuide(
                R.string.duck_n0_emotion,
                R.drawable.frame_duck_no_emotion_1,
                listOf(
                    R.drawable.frame_duck_no_emotion_1,
                    R.drawable.frame_duck_no_emotion_2,
                    R.drawable.frame_duck_no_emotion_3,
                    R.drawable.frame_duck_no_emotion_4,
                    R.drawable.frame_duck_no_emotion_5,
                    R.drawable.frame_duck_no_emotion_6,
                    R.drawable.frame_duck_no_emotion_7,
                    R.drawable.frame_duck_no_emotion_8,
                    R.drawable.frame_duck_no_emotion_9,
                    R.drawable.frame_duck_no_emotion_10,
                    R.drawable.frame_duck_no_emotion_11,
                    R.drawable.frame_duck_no_emotion_12,
                )
            ),

            AnimationGuide(
                R.string.duck_n0_emotion,
                R.drawable.frame_duck_no_emotion_1,
                listOf(
                    R.drawable.frame_duck_no_emotion_1,
                    R.drawable.frame_duck_no_emotion_2,
                    R.drawable.frame_duck_no_emotion_3,
                    R.drawable.frame_duck_no_emotion_4,
                    R.drawable.frame_duck_no_emotion_5,
                    R.drawable.frame_duck_no_emotion_6,
                    R.drawable.frame_duck_no_emotion_7,
                    R.drawable.frame_duck_no_emotion_8,
                    R.drawable.frame_duck_no_emotion_9,
                    R.drawable.frame_duck_no_emotion_10,
                    R.drawable.frame_duck_no_emotion_11,
                    R.drawable.frame_duck_no_emotion_12,
                )
            ),

            AnimationGuide(
                R.string.i_am_exercising,
                R.drawable.frame_i_am_exercising_1,
                listOf(
                    R.drawable.frame_i_am_exercising_1,
                    R.drawable.frame_i_am_exercising_2,
                    R.drawable.frame_i_am_exercising_3,
                    R.drawable.frame_i_am_exercising_4,
                    R.drawable.frame_i_am_exercising_5,
                    R.drawable.frame_i_am_exercising_6,
                    R.drawable.frame_i_am_exercising_7,
                    R.drawable.frame_i_am_exercising_8,
                    R.drawable.frame_i_am_exercising_9,
                    R.drawable.frame_i_am_exercising_10,
                    R.drawable.frame_i_am_exercising_11,
                    R.drawable.frame_i_am_exercising_12,
                    R.drawable.frame_i_am_exercising_13,
                    R.drawable.frame_i_am_exercising_14,
                )
            ),

            AnimationGuide(
                R.string.lazy_cat,
                R.drawable.frame_lazy_cat_1,
                listOf(
                    R.drawable.frame_lazy_cat_1,
                    R.drawable.frame_lazy_cat_2,
                    R.drawable.frame_lazy_cat_3,
                    R.drawable.frame_lazy_cat_4,
                    R.drawable.frame_lazy_cat_5,
                    R.drawable.frame_lazy_cat_6,
                    R.drawable.frame_lazy_cat_7,
                    R.drawable.frame_lazy_cat_8,
                    R.drawable.frame_lazy_cat_9,
                )
            ),

            AnimationGuide(
                R.string.no_emotion,
                R.drawable.frame_no_emotion_1,
                listOf(
                    R.drawable.frame_no_emotion_1,
                    R.drawable.frame_no_emotion_2,
                    R.drawable.frame_no_emotion_3,
                    R.drawable.frame_no_emotion_4,
                    R.drawable.frame_no_emotion_5,
                    R.drawable.frame_no_emotion_6,
                    R.drawable.frame_no_emotion_7,
                    R.drawable.frame_no_emotion_8,
                )
            ),

            AnimationGuide(
                R.string.on_fire,
                R.drawable.frame_on_fire_1,
                listOf(
                    R.drawable.frame_on_fire_1,
                    R.drawable.frame_on_fire_2,
                    R.drawable.frame_on_fire_3,
                    R.drawable.frame_on_fire_4,
                    R.drawable.frame_on_fire_5,
                    R.drawable.frame_on_fire_6,
                    R.drawable.frame_on_fire_7,
                    R.drawable.frame_on_fire_8,
                    R.drawable.frame_on_fire_9,
                    R.drawable.frame_on_fire_10,
                    R.drawable.frame_on_fire_11,
                    R.drawable.frame_on_fire_12,
                )
            ),

            AnimationGuide(
                R.string.rabit,
                R.drawable.frame_rabit_1,
                listOf(
                    R.drawable.frame_rabit_1,
                    R.drawable.frame_rabit_2,
                    R.drawable.frame_rabit_3,
                    R.drawable.frame_rabit_4,
                    R.drawable.frame_rabit_5,
                    R.drawable.frame_rabit_6,
                    R.drawable.frame_rabit_7,
                    R.drawable.frame_rabit_8,
                    R.drawable.frame_rabit_9,
                    R.drawable.frame_rabit_10,
                )
            ),

            AnimationGuide(
                R.string.try_to_stolen,
                R.drawable.frame_try_to_stolen_1,
                listOf(
                    R.drawable.frame_try_to_stolen_1,
                    R.drawable.frame_try_to_stolen_2,
                    R.drawable.frame_try_to_stolen_3,
                    R.drawable.frame_try_to_stolen_4,
                    R.drawable.frame_try_to_stolen_5,
                    R.drawable.frame_try_to_stolen_6,
                    R.drawable.frame_try_to_stolen_7,
                    R.drawable.frame_try_to_stolen_8,
                    R.drawable.frame_try_to_stolen_9,
                    R.drawable.frame_try_to_stolen_10,
                    R.drawable.frame_try_to_stolen_11,
                    R.drawable.frame_try_to_stolen_12,
                    R.drawable.frame_try_to_stolen_13,
                )
            ),
            AnimationGuide(
                R.string.what_the_heck,
                R.drawable.frame_what_the_heck_1,
                listOf(
                    R.drawable.frame_what_the_heck_1,
                    R.drawable.frame_what_the_heck_2,
                    R.drawable.frame_what_the_heck_3,
                    R.drawable.frame_what_the_heck_4,
                    R.drawable.frame_what_the_heck_5,
                    R.drawable.frame_what_the_heck_6,
                    R.drawable.frame_what_the_heck_7,
                    R.drawable.frame_what_the_heck_8,
                    R.drawable.frame_what_the_heck_9,
                )
            ),
        )
    }

    fun listAnime(): MutableList<AnimationGuide> {
        return mutableListOf(
            AnimationGuide(
                R.string.neko_dance,
                R.drawable.frame_neko_dance_1,
                listOf(
                    R.drawable.frame_neko_dance_1,
                    R.drawable.frame_neko_dance_2,
                    R.drawable.frame_neko_dance_3,
                    R.drawable.frame_neko_dance_4,
                    R.drawable.frame_neko_dance_5,
                    R.drawable.frame_neko_dance_6,
                    R.drawable.frame_neko_dance_7,
                    R.drawable.frame_neko_dance_8,
                )
            ),

            AnimationGuide(
                R.string.anime,
                R.drawable.frame_anime_1_1,
                listOf(
                    R.drawable.frame_anime_1_1,
                    R.drawable.frame_anime_1_2,
                )
            ),

            AnimationGuide(
                R.string.anime,
                R.drawable.frame_anime_2_1,
                listOf(
                    R.drawable.frame_anime_2_1,
                    R.drawable.frame_anime_2_2,
                    R.drawable.frame_anime_2_3,
                    R.drawable.frame_anime_2_4,
                    R.drawable.frame_anime_2_5,
                    R.drawable.frame_anime_2_6,
                )
            ),

            AnimationGuide(
                R.string.anime,
                R.drawable.frame_anime_3_1,
                listOf(
                    R.drawable.frame_anime_3_1,
                    R.drawable.frame_anime_3_2,
                    R.drawable.frame_anime_3_3,
                    R.drawable.frame_anime_3_4,
                    R.drawable.frame_anime_3_5,
                    R.drawable.frame_anime_3_6,
                    R.drawable.frame_anime_3_7,
                    R.drawable.frame_anime_3_8,
                    R.drawable.frame_anime_3_9,
                    R.drawable.frame_anime_3_10,
                    R.drawable.frame_anime_3_11,
                    R.drawable.frame_anime_3_12,
                    R.drawable.frame_anime_3_13,
                    R.drawable.frame_anime_3_14,
                    R.drawable.frame_anime_3_15,
                    R.drawable.frame_anime_3_16,
                )
            ),

            AnimationGuide(
                R.string.anime,
                R.drawable.frame_anime_4_1,
                listOf(
                    R.drawable.frame_anime_4_1,
                    R.drawable.frame_anime_4_2,
                    R.drawable.frame_anime_4_3,
                    R.drawable.frame_anime_4_4,
                    R.drawable.frame_anime_4_5,
                    R.drawable.frame_anime_4_6,
                    R.drawable.frame_anime_4_7,
                    R.drawable.frame_anime_4_8,
                )
            ),

            AnimationGuide(
                R.string.mob_dumb,
                R.drawable.frame_mob_dumb_1,
                listOf(
                    R.drawable.frame_mob_dumb_1,
                    R.drawable.frame_mob_dumb_2,
                    R.drawable.frame_mob_dumb_3,
                    R.drawable.frame_mob_dumb_4,
                    R.drawable.frame_mob_dumb_5,
                )
            ),

            AnimationGuide(
                R.string.oishi,
                R.drawable.frame_oishi_1,
                listOf(
                    R.drawable.frame_oishi_1,
                    R.drawable.frame_oishi_2,
                    R.drawable.frame_oishi_3,
                    R.drawable.frame_oishi_4,
                )
            ),

            AnimationGuide(
                R.string.sorry_sumimasen,
                R.drawable.frame_sorry_sumimasen_1,
                listOf(
                    R.drawable.frame_sorry_sumimasen_1,
                    R.drawable.frame_sorry_sumimasen_2,
                    R.drawable.frame_sorry_sumimasen_3,
                    R.drawable.frame_sorry_sumimasen_4,
                    R.drawable.frame_sorry_sumimasen_5,
                    R.drawable.frame_sorry_sumimasen_6,
                    R.drawable.frame_sorry_sumimasen_7,
                    R.drawable.frame_sorry_sumimasen_8,
                )
            ),

            AnimationGuide(
                R.string.sorry_sumimasen,
                R.drawable.frame_sorry_sumimasen_1,
                listOf(
                    R.drawable.frame_sorry_sumimasen_1,
                    R.drawable.frame_sorry_sumimasen_2,
                    R.drawable.frame_sorry_sumimasen_3,
                    R.drawable.frame_sorry_sumimasen_4,
                    R.drawable.frame_sorry_sumimasen_5,
                    R.drawable.frame_sorry_sumimasen_6,
                    R.drawable.frame_sorry_sumimasen_7,
                    R.drawable.frame_sorry_sumimasen_8,
                )
            ),
            AnimationGuide(
                R.string.urushi_desu,
                R.drawable.frame_urushi_desu_1,
                listOf(
                    R.drawable.frame_urushi_desu_1,
                    R.drawable.frame_urushi_desu_2,
                    R.drawable.frame_urushi_desu_3,
                    R.drawable.frame_urushi_desu_4,
                    R.drawable.frame_urushi_desu_5,
                    R.drawable.frame_urushi_desu_6,
                    R.drawable.frame_urushi_desu_7,
                    R.drawable.frame_urushi_desu_8,
                    R.drawable.frame_urushi_desu_9,
                    R.drawable.frame_urushi_desu_10,
                    R.drawable.frame_urushi_desu_11,
                    R.drawable.frame_urushi_desu_12,
                    R.drawable.frame_urushi_desu_13,
                    R.drawable.frame_urushi_desu_14
                )
            ),
            AnimationGuide(
                R.string.yayyh,
                R.drawable.frame_yayh_1,
                listOf(
                    R.drawable.frame_yayh_1,
                    R.drawable.frame_yayh_2,
                    R.drawable.frame_yayh_3,
                    R.drawable.frame_yayh_4,
                    R.drawable.frame_yayh_5,
                )
            ),
        )
    }

    fun listCartoon(): MutableList<AnimationGuide> {
        return mutableListOf(
            AnimationGuide(
                R.string.mermaid_hello,
                R.drawable.frame_mermaid_hello_1,
                listOf(
                    R.drawable.frame_mermaid_hello_1,
                    R.drawable.frame_mermaid_hello_2,
                    R.drawable.frame_mermaid_hello_3,
                    R.drawable.frame_mermaid_hello_4,
                    R.drawable.frame_mermaid_hello_5,
                    R.drawable.frame_mermaid_hello_6,
                    R.drawable.frame_mermaid_hello_7,
                    R.drawable.frame_mermaid_hello_8,
                    R.drawable.frame_mermaid_hello_9,
                )
            ),AnimationGuide(
                R.string.mermaid_hello,
                R.drawable.frame_mermaid_hello_1,
                listOf(
                    R.drawable.frame_mermaid_hello_1,
                    R.drawable.frame_mermaid_hello_2,
                    R.drawable.frame_mermaid_hello_3,
                    R.drawable.frame_mermaid_hello_4,
                    R.drawable.frame_mermaid_hello_5,
                    R.drawable.frame_mermaid_hello_6,
                    R.drawable.frame_mermaid_hello_7,
                    R.drawable.frame_mermaid_hello_8,
                    R.drawable.frame_mermaid_hello_9,
                )
            ),
            AnimationGuide(
                R.string.no_emotion,
                R.drawable.frame_no_emotion_1_1,
                listOf(
                    R.drawable.frame_no_emotion_1_1,
                    R.drawable.frame_no_emotion_1_2,
                    R.drawable.frame_no_emotion_1_3,
                    R.drawable.frame_no_emotion_1_4,
                    R.drawable.frame_no_emotion_1_5,
                    R.drawable.frame_no_emotion_1_6,
                    R.drawable.frame_no_emotion_1_7,
                    R.drawable.frame_no_emotion_1_8,
                    R.drawable.frame_no_emotion_1_9,
                    R.drawable.frame_no_emotion_1_10,
                    R.drawable.frame_no_emotion_1_11,
                    R.drawable.frame_no_emotion_1_12,
                    R.drawable.frame_no_emotion_1_13,
                    R.drawable.frame_no_emotion_1_14,
                    R.drawable.frame_no_emotion_1_15,
                    R.drawable.frame_no_emotion_1_16,
                )
            ),

            AnimationGuide(
                R.string.te_he,
                R.drawable.frame_te_he_1,
                listOf(
                    R.drawable.frame_te_he_1,
                    R.drawable.frame_te_he_2,
                    R.drawable.frame_te_he_3,
                    R.drawable.frame_te_he_4,
                    R.drawable.frame_te_he_5,
                    R.drawable.frame_te_he_6,
                    R.drawable.frame_te_he_7,
                    R.drawable.frame_te_he_8,
                    R.drawable.frame_te_he_9,
                    R.drawable.frame_te_he_10,
                    R.drawable.frame_te_he_11,
                    R.drawable.frame_te_he_12,
                )
            ),

            AnimationGuide(
                R.string.is_that_you,
                R.drawable.frame_is_that_you_1,
                listOf(
                    R.drawable.frame_is_that_you_1,
                    R.drawable.frame_is_that_you_2,
                    R.drawable.frame_is_that_you_3,
                    R.drawable.frame_is_that_you_4,
                    R.drawable.frame_is_that_you_5,
                    R.drawable.frame_is_that_you_6,
                    R.drawable.frame_is_that_you_7,
                    R.drawable.frame_is_that_you_8,
                    R.drawable.frame_is_that_you_9,
                    R.drawable.frame_is_that_you_10,
                    R.drawable.frame_is_that_you_11,
                    R.drawable.frame_is_that_you_12,
                    R.drawable.frame_is_that_you_13,
                )
            ),

            AnimationGuide(
                R.string.cause_you,
                R.drawable.frame_cause_you_1,
                listOf(
                    R.drawable.frame_cause_you_1,
                    R.drawable.frame_cause_you_2,
                    R.drawable.frame_cause_you_3,
                    R.drawable.frame_cause_you_4,
                    R.drawable.frame_cause_you_5,
                    R.drawable.frame_cause_you_6,
                    R.drawable.frame_cause_you_7,
                    R.drawable.frame_cause_you_8,
                    R.drawable.frame_cause_you_9,
                )
            ),
            AnimationGuide(
                R.string.cartoon,
                R.drawable.frame_cartoon_1,
                listOf(
                    R.drawable.frame_cartoon_1,
                    R.drawable.frame_cartoon_2,
                    R.drawable.frame_cartoon_3,
                    R.drawable.frame_cartoon_4,
                    R.drawable.frame_cartoon_5,
                    R.drawable.frame_cartoon_6,
                    R.drawable.frame_cartoon_7,
                    R.drawable.frame_cartoon_8,
                    R.drawable.frame_cartoon_9,
                    R.drawable.frame_cartoon_10,
                )
            ),

            AnimationGuide(
                R.string.wahhh,
                R.drawable.frame_wahhh_1,
                listOf(
                    R.drawable.frame_wahhh_1,
                    R.drawable.frame_wahhh_2,
                    R.drawable.frame_wahhh_3,
                )
            ),

            AnimationGuide(
                R.string.fall_in_love,
                R.drawable.frame_fall_in_love_1,
                listOf(
                    R.drawable.frame_fall_in_love_1,
                    R.drawable.frame_fall_in_love_2,
                    R.drawable.frame_fall_in_love_3,
                    R.drawable.frame_fall_in_love_4,
                    R.drawable.frame_fall_in_love_5,
                    R.drawable.frame_fall_in_love_6,
                    R.drawable.frame_fall_in_love_7,
                    R.drawable.frame_fall_in_love_8,
                    R.drawable.frame_fall_in_love_9,
                    R.drawable.frame_fall_in_love_10,
                    R.drawable.frame_fall_in_love_11,
                    R.drawable.frame_fall_in_love_12,
                )
            ),

            AnimationGuide(
                R.string.clock_too_late,
                R.drawable.frame_clock_too_late_1,
                listOf(
                    R.drawable.frame_clock_too_late_1,
                    R.drawable.frame_clock_too_late_2,
                    R.drawable.frame_clock_too_late_3,
                    R.drawable.frame_clock_too_late_4,
                    R.drawable.frame_clock_too_late_5,
                    R.drawable.frame_clock_too_late_6,
                    R.drawable.frame_clock_too_late_7,
                    R.drawable.frame_clock_too_late_8,
                    R.drawable.frame_clock_too_late_9,
                    R.drawable.frame_clock_too_late_10,
                    R.drawable.frame_clock_too_late_11,
                    R.drawable.frame_clock_too_late_12,
                )
            ),

            AnimationGuide(
                R.string.housework_enjoy,
                R.drawable.frame_housework_enjoy_1,
                listOf(
                    R.drawable.frame_housework_enjoy_1,
                    R.drawable.frame_housework_enjoy_2,
                    R.drawable.frame_housework_enjoy_3,
                    R.drawable.frame_housework_enjoy_4,
                    R.drawable.frame_housework_enjoy_5,
                    R.drawable.frame_housework_enjoy_6,
                    R.drawable.frame_housework_enjoy_7,
                    R.drawable.frame_housework_enjoy_8,
                    R.drawable.frame_housework_enjoy_9,
                    R.drawable.frame_housework_enjoy_10,
                    R.drawable.frame_housework_enjoy_11,
                    R.drawable.frame_housework_enjoy_12,
                    R.drawable.frame_housework_enjoy_13,
                    R.drawable.frame_housework_enjoy_14,
                )
            ),


            AnimationGuide(
                R.string.childhood_enjoy,
                R.drawable.frame_childhood_enjoy_1,
                listOf(
                    R.drawable.frame_childhood_enjoy_1,
                    R.drawable.frame_childhood_enjoy_2,
                    R.drawable.frame_childhood_enjoy_3,
                    R.drawable.frame_childhood_enjoy_4,
                    R.drawable.frame_childhood_enjoy_5,
                    R.drawable.frame_childhood_enjoy_6,
                    R.drawable.frame_childhood_enjoy_7,
                    R.drawable.frame_childhood_enjoy_8,
                    R.drawable.frame_childhood_enjoy_9,
                    R.drawable.frame_childhood_enjoy_10,
                    R.drawable.frame_childhood_enjoy_11,
                    R.drawable.frame_childhood_enjoy_12,
                )
            ),

            AnimationGuide(
                R.string.madam_cool,
                R.drawable.frame_madam_cool_1,
                listOf(
                    R.drawable.frame_madam_cool_1,
                    R.drawable.frame_madam_cool_2,
                    R.drawable.frame_madam_cool_3,
                    R.drawable.frame_madam_cool_4,
                    R.drawable.frame_madam_cool_5,
                    R.drawable.frame_madam_cool_6,
                    R.drawable.frame_madam_cool_7,
                    R.drawable.frame_madam_cool_8,
                    R.drawable.frame_madam_cool_9,
                    R.drawable.frame_madam_cool_10,
                    R.drawable.frame_madam_cool_11,
                    R.drawable.frame_madam_cool_12,
                    R.drawable.frame_madam_cool_13,
                    R.drawable.frame_madam_cool_14,
                )
            ),

            AnimationGuide(
                R.string.cute,
                R.drawable.frame_cute_1,
                listOf(
                    R.drawable.frame_cute_1,
                    R.drawable.frame_cute_2,
                    R.drawable.frame_cute_3,
                    R.drawable.frame_cute_4,
                    R.drawable.frame_cute_5,
                    R.drawable.frame_cute_6,
                    R.drawable.frame_cute_7,
                    R.drawable.frame_cute_8,
                    R.drawable.frame_cute_9,
                    R.drawable.frame_cute_10,
                    R.drawable.frame_cute_11,
                )
            ),
        )
    }


    fun listTypeAnimationGuide(): MutableList<TypeAnimationGuide> {
        return mutableListOf(
            TypeAnimationGuide(
                R.string.beginner,
                R.drawable.frame_beginer_1,
                listBeginner()
            ),
            TypeAnimationGuide(
                R.string.animal,
                R.drawable.frame_cat_1_2,
                listAnimal()
            ),
            TypeAnimationGuide(
                R.string.anime,
                R.drawable.frame_neko_dance_1,
                listAnime()
            ),
            TypeAnimationGuide(
                R.string.cartoon,
                R.drawable.frame_cartoon_1,
                listCartoon()
            ),
        )
    }
}